### ISSUE TITLE
Readme Changes.

### ISSUE THREAD

**Issue by DevNigam** [BullyBoo/TextCounter#2]
Please change the readme. Defined classes are not found in library.

**Comment by BullyBoo** [comment]
which class?

**Comment by EpariNigam** [comment]
Actually its mentioned as `TextAnimator` which should be `TextCounter`.

**Comment by BullyBoo** [comment]
Has been fixed, thank you)

**Comment by EpariNigam** [comment]
Hello, there are again some changes need to be done.

**To use text counter you need to call TextAnimator.newBuilder() and set properties of animation**

Please correct this line.

**Comment by BullyBoo** [comment]
Yeah, thank you.
I changed it again)
Sorry c:
